# Generated by Django 4.2.5 on 2023-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='meditation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
