# Generated by Django 4.2.5 on 2023-10-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
