# Generated by Django 4.2.5 on 2023-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_activity_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='meditation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
