# Generated by Django 4.2.5 on 2023-10-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_activity_meditation_type_alter_activity_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='emotion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
