# Generated by Django 4.2.5 on 2023-10-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_activity_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='meditation_type',
            new_name='technique',
        ),
    ]
