# Generated by Django 4.2.5 on 2023-10-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='emotion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
