# Generated by Django 4.2.5 on 2023-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_community_communityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuser',
            name='status',
            field=models.CharField(default='joined', max_length=50),
        ),
    ]
