# Generated by Django 4.2.5 on 2023-11-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_communityuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='app.activity')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='app.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
