# Generated by Django 4.2.5 on 2023-11-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_communitypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypost',
            old_name='title',
            new_name='name',
        ),
    ]
