# Generated by Django 4.2.5 on 2023-11-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_title_communitypost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='communitypost',
            old_name='name',
            new_name='title',
        ),
    ]
