# Generated by Django 4.2.5 on 2023-11-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_title_community_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='user',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='community_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='app.communityuser'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.communitypost')),
                ('community_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_likes', to='app.communityuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.communitypost')),
                ('community_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_comments', to='app.communityuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
